version: "3.3"
services:
  pastr:
    container_name: pastr
    image: pastr
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PASTR_HOST=http://localhost:3000
      - PASTR_KEY_LENGTH=4
    volumes:
      - "./data.db:/app/data.db"
