version: "3.3"
services:
  pastr:
    container_name: pastr
    image: pastr
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PASTR_DATA_PATH=/app/data
      - PASTR_KEY_LENGTH=4
      - PASTR_USE_FORWARDED_HEADERS=false
    volumes:
      - "./data:/app/data"
